### ISSUE TITLE
TimeText not working as intended

### ISSUE THREAD

**Issue by Paoleddu** [feduss/Tomatimer#2]
As for the title, TimeText doesn't work as intended:
if I've started a tomato session and the app is minimized or the screen turns off, the next time I open the app to see the remaining time of the timer, TimeText resets and starts counting from that moment.
I.e.: if I start a pomodoro session of 30 minutes at 12AM and then I let the screen turn off, if let's say I open the app again at 12:10AM, TimeText would calculate the expected end of the timer starting from 12:10 and not from 12, giving 12:40 as the predicted end of the session.

**Comment by feduss** [comment]
Thanks for this issue @Paoleddu . I pushed a a test fix for this bug and a new 1.1.2 version in play store (internal test channel). Let me know if this fix resolved the problem.

**Comment by feduss** [comment]
Closed for inactivity @Paoleddu. Feel free to re-open it if needed.
